export function translateTeamName(name: string | null | undefined, lang: string): string {
  if (!name) return '';
  const cleanName = name.trim();

  const translations: Record<string, Record<string, string>> = {
    'England': {
      ES: 'Inglaterra',
      EN: 'England',
      FR: 'Angleterre',
      IT: 'Inghilterra',
      JA: 'イングランド',
      KO: '잉글랜드',
    },
    'Croatia': {
      ES: 'Croacia',
      EN: 'Croatia',
      FR: 'Croatie',
      IT: 'Croazia',
      JA: 'クロアチア',
      KO: '크로아티아',
    },
    'Portugal': {
      ES: 'Portugal',
      EN: 'Portugal',
      FR: 'Portugal',
      IT: 'Portogallo',
      JA: 'ポルトガル',
      KO: '포르투갈',
    },
    'Congo DR': {
      ES: 'R.D. Congo',
      EN: 'Congo DR',
      FR: 'R.D. Congo',
      IT: 'R.D. Congo',
      JA: 'コンゴ民主共和国',
      KO: '콩고민주공화국',
    },
    'Ghana': {
      ES: 'Ghana',
      EN: 'Ghana',
      FR: 'Ghana',
      IT: 'Ghana',
      JA: 'ガーナ',
      KO: '가나',
    },
    'Panama': {
      ES: 'Panamá',
      EN: 'Panama',
      FR: 'Panama',
      IT: 'Panama',
      JA: 'パナマ',
      KO: '파나마',
    },
    'Uzbekistan': {
      ES: 'Uzbekistán',
      EN: 'Uzbekistan',
      FR: 'Ouzbékistan',
      IT: 'Uzbekistan',
      JA: 'ウズベキスタン',
      KO: '우즈베키스탄',
    },
    'Colombia': {
      ES: 'Colombia',
      EN: 'Colombia',
      FR: 'Colombie',
      IT: 'Colombia',
      JA: 'コロンビア',
      KO: '콜롬비아',
    },
    'Argentina': {
      ES: 'Argentina',
      EN: 'Argentina',
      FR: 'Argentine',
      IT: 'Argentina',
      JA: 'アルゼンチン',
      KO: '아르헨티나',
    },
    'Brazil': {
      ES: 'Brasil',
      EN: 'Brasil',
      FR: 'Brésil',
      IT: 'Brasile',
      JA: 'ブラジル',
      KO: '브라질',
    },
    'Germany': {
      ES: 'Alemania',
      EN: 'Germany',
      FR: 'Allemagne',
      IT: 'Germania',
      JA: 'ドイツ',
      KO: '독일',
    },
    'France': {
      ES: 'Francia',
      EN: 'France',
      FR: 'France',
      IT: 'Francia',
      JA: 'フランス',
      KO: '프랑스',
    },
    'Spain': {
      ES: 'España',
      EN: 'Spain',
      FR: 'Espagne',
      IT: 'Spagna',
      JA: 'スペイン',
      KO: '스페인',
    },
    'Italy': {
      ES: 'Italia',
      EN: 'Italy',
      FR: 'Italie',
      IT: 'Italia',
      JA: 'イタリア',
      KO: '이탈리아',
    },
    'Netherlands': {
      ES: 'Países Bajos',
      EN: 'Netherlands',
      FR: 'Pays-Bas',
      IT: 'Paesi Bassi',
      JA: 'オランダ',
      KO: '네덜란드',
    },
    'Belgium': {
      ES: 'Bélgica',
      EN: 'Belgium',
      FR: 'Belgique',
      IT: 'Belgio',
      JA: 'ベルギー',
      KO: '벨기에',
    },
    'Uruguay': {
      ES: 'Uruguay',
      EN: 'Uruguay',
      FR: 'Uruguay',
      IT: 'Uruguay',
      JA: 'ウルグアイ',
      KO: '우루과이',
    },
    'Mexico': {
      ES: 'México',
      EN: 'Mexico',
      FR: 'Mexique',
      IT: 'Messico',
      JA: 'メキシコ',
      KO: '멕시코',
    },
    'United States': {
      ES: 'Estados Unidos',
      EN: 'United States',
      FR: 'États-Unis',
      IT: 'Stati Uniti',
      JA: 'アメリカ',
      KO: '미국',
    },
    'USA': {
      ES: 'Estados Unidos',
      EN: 'United States',
      FR: 'États-Unis',
      IT: 'Stati Uniti',
      JA: 'アメリカ',
      KO: '미국',
    },
    'Canada': {
      ES: 'Canadá',
      EN: 'Canada',
      FR: 'Canada',
      IT: 'Canada',
      JA: 'カナダ',
      KO: '캐나다',
    },
    'Japan': {
      ES: 'Japón',
      EN: 'Japan',
      FR: 'Japon',
      IT: 'Giappone',
      JA: '日本',
      KO: '일본',
    },
    'South Korea': {
      ES: 'Corea del Sur',
      EN: 'South Korea',
      FR: 'Corée du Sud',
      IT: 'Corea del Sud',
      JA: '韓国',
      KO: '대한민국',
    },
    'Korea Republic': {
      ES: 'Corea del Sur',
      EN: 'South Korea',
      FR: 'Corée du Sud',
      IT: 'Corea del Sud',
      JA: '韓国',
      KO: '대한민국',
    },
    'Morocco': {
      ES: 'Marruecos',
      EN: 'Morocco',
      FR: 'Maroc',
      IT: 'Marocco',
      JA: 'モロッコ',
      KO: '모로코',
    },
    'Senegal': {
      ES: 'Senegal',
      EN: 'Senegal',
      FR: 'Sénégal',
      IT: 'Senegal',
      JA: 'セネガル',
      KO: '세네갈',
    },
    'Cameroon': {
      ES: 'Camerún',
      EN: 'Cameroon',
      FR: 'Cameroun',
      IT: 'Camerun',
      JA: 'カメルーン',
      KO: '카메룬',
    },
    'Ecuador': {
      ES: 'Ecuador',
      EN: 'Ecuador',
      FR: 'Équateur',
      IT: 'Ecuador',
      JA: 'エクアドル',
      KO: '에콰도르',
    },
    'Peru': {
      ES: 'Perú',
      EN: 'Peru',
      FR: 'Pérou',
      IT: 'Perù',
      JA: 'ペルー',
      KO: '페루',
    },
    'Chile': {
      ES: 'Chile',
      EN: 'Chile',
      FR: 'Chili',
      IT: 'Cile',
      JA: 'チリ',
      KO: '칠레',
    },
    'Poland': {
      ES: 'Polonia',
      EN: 'Poland',
      FR: 'Pologne',
      IT: 'Polonia',
      JA: 'ポーランド',
      KO: '폴란드',
    },
    'Switzerland': {
      ES: 'Suiza',
      EN: 'Switzerland',
      FR: 'Suisse',
      IT: 'Svizzera',
      JA: 'スイス',
      KO: '스위스',
    },
    'Sweden': {
      ES: 'Suecia',
      EN: 'Sweden',
      FR: 'Suède',
      IT: 'Svezia',
      JA: 'スウェーデン',
      KO: '스웨덴',
    },
    'Ukraine': {
      ES: 'Ucrania',
      EN: 'Ukraine',
      FR: 'Ukraine',
      IT: 'Ucraina',
      JA: 'ウズベキスタン',
      KO: '우크라이나',
    },
    'Denmark': {
      ES: 'Dinamarca',
      EN: 'Denmark',
      FR: 'Danemark',
      IT: 'Danimarca',
      JA: 'デンマーク',
      KO: '덴마크',
    },
    'Saudi Arabia': {
      ES: 'Arabia Saudita',
      EN: 'Saudi Arabia',
      FR: 'Arabie Saoudite',
      IT: 'Arabia Saudita',
      JA: 'サウジアラビア',
      KO: '사우디아라비아',
    },
    'Egypt': {
      ES: 'Egipto',
      EN: 'Egypt',
      FR: 'Égypte',
      IT: 'Egitto',
      JA: 'エジプト',
      KO: '이집트',
    },
    'Iran': {
      ES: 'Irán',
      EN: 'Iran',
      FR: 'Iran',
      IT: 'Iran',
      JA: 'イラン',
      KO: '이란',
    },
    'Costa Rica': {
      ES: 'Costa Rica',
      EN: 'Costa Rica',
      FR: 'Costa Rica',
      IT: 'Costa Rica',
      JA: 'コスタリカ',
      KO: '코스타리카',
    },
    'Australia': {
      ES: 'Australia',
      EN: 'Australia',
      FR: 'Australie',
      IT: 'Australia',
      JA: 'オーストラリア',
      KO: '호주',
    },
    'New Zealand': {
      ES: 'Nueva Zelanda',
      EN: 'New Zealand',
      FR: 'Nouvelle-Zélande',
      IT: 'Nuova Zelanda',
      JA: 'ニュージーランド',
      KO: '뉴질랜드',
    },
    'Nigeria': {
      ES: 'Nigeria',
      EN: 'Nigeria',
      FR: 'Nigéria',
      IT: 'Nigeria',
      JA: 'ナイジェリア',
      KO: '나이지리아',
    },
    'Tunisia': {
      ES: 'Túnez',
      EN: 'Tunisia',
      FR: 'Tunisie',
      IT: 'Tunisia',
      JA: 'チュニジア',
      KO: '튀니지',
    },
    'Qatar': {
      ES: 'Catar',
      EN: 'Qatar',
      FR: 'Qatar',
      IT: 'Qatar',
      JA: 'カタール',
      KO: '카타르',
    },
    'Serbia': {
      ES: 'Serbia',
      EN: 'Serbia',
      FR: 'Serbie',
      IT: 'Serbia',
      JA: 'セルビア',
      KO: '세르비아',
    },
    'Wales': {
      ES: 'Gales',
      EN: 'Wales',
      FR: 'Pays de Galles',
      IT: 'Galles',
      JA: 'ウェールズ',
      KO: '웨일스',
    },
    'Austria': {
      ES: 'Austria',
      EN: 'Austria',
      FR: 'Autriche',
      IT: 'Austria',
      JA: 'オーストリア',
      KO: '오스트リア',
    },
    'Turkey': {
      ES: 'Turquía',
      EN: 'Turkey',
      FR: 'Turquie',
      IT: 'Turchia',
      JA: 'トルコ',
      KO: '터키',
    },
    'Czech Republic': {
      ES: 'República Checa',
      EN: 'Czech Republic',
      FR: 'République Tchèque',
      IT: 'Repubblica Ceca',
      JA: 'チェコ',
      KO: '체코',
    },
    'Ivory Coast': {
      ES: 'Costa de Marfil',
      EN: 'Ivory Coast',
      FR: 'Côte d’Ivoire',
      IT: 'Costa d’Avorio',
      JA: 'コートジボワール',
      KO: '코트디부아르',
    },
    'Venezuela': {
      ES: 'Venezuela',
      EN: 'Venezuela',
      FR: 'Venezuela',
      IT: 'Venezuela',
      JA: 'ベネズエラ',
      KO: '베네수엘라',
    },
    'Paraguay': {
      ES: 'Paraguay',
      EN: 'Paraguay',
      FR: 'Paraguay',
      IT: 'Paraguay',
      JA: 'パラグアイ',
      KO: '파라과이',
    },
    'Bolivia': {
      ES: 'Bolivia',
      EN: 'Bolivia',
      FR: 'Bolivie',
      IT: 'Bolivia',
      JA: 'ボリビア',
      KO: '볼리비아',
    },
    'Greece': {
      ES: 'Grecia',
      EN: 'Greece',
      FR: 'Grèce',
      IT: 'Grecia',
      JA: 'ギリシャ',
      KO: '그리스',
    },
    'Hungary': {
      ES: 'Hungría',
      EN: 'Hungary',
      FR: 'Hongrie',
      IT: 'Ungheria',
      JA: 'ハンガリー',
      KO: '헝가리',
    },
    'Slovakia': {
      ES: 'Eslovaquia',
      EN: 'Slovakia',
      FR: 'Slovaquie',
      IT: 'Slovacchia',
      JA: 'スロバキア',
      KO: '슬로바키아',
    },
    'Slovenia': {
      ES: 'Eslovenia',
      EN: 'Slovenia',
      FR: 'Slovénie',
      IT: 'Slovenia',
      JA: 'スロベニア',
      KO: '슬로베니아',
    },
    'Romania': {
      ES: 'Rumania',
      EN: 'Romania',
      FR: 'Roumanie',
      IT: 'Romania',
      JA: 'ルーマニア',
      KO: '루마니아',
    },
    'Georgia': {
      ES: 'Georgia',
      EN: 'Georgia',
      FR: 'Géorgie',
      IT: 'Georgia',
      JA: 'ジョージア',
      KO: '조지아',
    },
    'Albania': {
      ES: 'Albania',
      EN: 'Albania',
      FR: 'Albanie',
      IT: 'Albania',
      JA: 'アルバニア',
      KO: '알바니아',
    },
    'Scotland': {
      ES: 'Escocia',
      EN: 'Scotland',
      FR: 'Écosse',
      IT: 'Scozia',
      JA: 'スコットランド',
      KO: '스코틀랜드',
    },
    'Ireland': {
      ES: 'Irlanda',
      EN: 'Ireland',
      FR: 'Irlande',
      IT: 'Irlanda',
      JA: 'アイルランド',
      KO: '아일랜드',
    },
    'Northern Ireland': {
      ES: 'Irlanda del Norte',
      EN: 'Northern Ireland',
      FR: 'Irlande du Nord',
      IT: 'Irlanda del Nord',
      JA: '北アイルランド',
      KO: '북아일랜드',
    },
    'Iceland': {
      ES: 'Islandia',
      EN: 'Iceland',
      FR: 'Islande',
      IT: 'Islandia',
      JA: 'アイスランド',
      KO: '아이슬란드',
    },
    'Norway': {
      ES: 'Noruega',
      EN: 'Norway',
      FR: 'Norvège',
      IT: 'Norvegia',
      JA: 'ノルウェー',
      KO: '노르웨이',
    },
    'Finland': {
      ES: 'Finlandia',
      EN: 'Finland',
      FR: 'Finlande',
      IT: 'Finlandia',
      JA: 'フィンランド',
      KO: '핀란드',
    },
    'Honduras': {
      ES: 'Honduras',
      EN: 'Honduras',
      FR: 'Honduras',
      IT: 'Honduras',
      JA: 'ホンジュラス',
      KO: '온두라스',
    },
    'Jamaica': {
      ES: 'Jamaica',
      EN: 'Jamaica',
      FR: 'Jamaïque',
      IT: 'Giamaica',
      JA: 'ジャマイカ',
      KO: '자메이카',
    },
    'El Salvador': {
      ES: 'El Salvador',
      EN: 'El Salvador',
      FR: 'El Salvador',
      IT: 'El Salvador',
      JA: 'エルサルバドル',
      KO: '엘살바도르',
    },
    'Guatemala': {
      ES: 'Guatemala',
      EN: 'Guatemala',
      FR: 'Guatemala',
      IT: 'Guatemala',
      JA: 'グアテマラ',
      KO: '과테말라',
    },
    'South Africa': {
      ES: 'Sudáfrica',
      EN: 'South Africa',
      FR: 'Afrique du Sud',
      IT: 'Sudafrica',
      JA: '南アフリカ',
      KO: '남아프리카공화국',
    },
    'Algeria': {
      ES: 'Argelia',
      EN: 'Algeria',
      FR: 'Algérie',
      IT: 'Algeria',
      JA: 'アルジェリア',
      KO: '알제리',
    },
    'Mali': {
      ES: 'Mali',
      EN: 'Mali',
      FR: 'Mali',
      IT: 'Mali',
      JA: 'マリ',
      KO: '말리',
    },
    'Burkina Faso': {
      ES: 'Burkina Faso',
      EN: 'Burkina Faso',
      FR: 'Burkina Faso',
      IT: 'Burkina Faso',
      JA: 'ブルキナファソ',
      KO: '부르키나파소',
    },
    'Cape Verde': {
      ES: 'Cabo Verde',
      EN: 'Cape Verde',
      FR: 'Cap-Vert',
      IT: 'Capo Verde',
      JA: 'カーボベルデ',
      KO: '카보베르데',
    },
    'Guinea': {
      ES: 'Guinea',
      EN: 'Guinea',
      FR: 'Guinée',
      IT: 'Guinea',
      JA: 'ギニア',
      KO: '기니',
    },
    'Angola': {
      ES: 'Angola',
      EN: 'Angola',
      FR: 'Angola',
      IT: 'Angola',
      JA: 'アンゴラ',
      KO: '앙골라',
    },
    'Benin': {
      ES: 'Benín',
      EN: 'Benin',
      FR: 'Bénin',
      IT: 'Benin',
      JA: 'ベナン',
      KO: '베냉',
    },
    'Togo': {
      ES: 'Togo',
      EN: 'Togo',
      FR: 'Togo',
      IT: 'Togo',
      JA: 'トーゴ',
      KO: '토고',
    },
    'China': {
      ES: 'China',
      EN: 'China',
      FR: 'Chine',
      IT: 'Cina',
      JA: '中国',
      KO: '중국',
    },
    'Iraq': {
      ES: 'Irak',
      EN: 'Iraq',
      FR: 'Irak',
      IT: 'Iraq',
      JA: 'イラク',
      KO: '이라크',
    },
    'United Arab Emirates': {
      ES: 'Emiratos Árabes Unidos',
      EN: 'United Arab Emirates',
      FR: 'Émirats arabes unis',
      IT: 'Emirati Arabi Uniti',
      JA: 'アラブ首長国連邦',
      KO: '아랍에미리트',
    },
    'UAE': {
      ES: 'Emiratos Árabes Unidos',
      EN: 'United Arab Emirates',
      FR: 'Émirats arabes unis',
      IT: 'Emirati Arabi Uniti',
      JA: 'アラブ首長国連邦',
      KO: '아랍에미리트',
    },
    'Oman': {
      ES: 'Omán',
      EN: 'Oman',
      FR: 'Oman',
      IT: 'Oman',
      JA: 'オマーン',
      KO: '오만',
    },
    'Jordan': {
      ES: 'Jordania',
      EN: 'Jordan',
      FR: 'Jordanie',
      IT: 'Giordania',
      JA: 'ヨルダン',
      KO: '요르단',
    },
    'Bahrain': {
      ES: 'Baréin',
      EN: 'Bahrain',
      FR: 'Bahreïn',
      IT: 'Bahrein',
      JA: 'バーレーン',
      KO: '바레인',
    },
    'Syria': {
      ES: 'Siria',
      EN: 'Syria',
      FR: 'Syrie',
      IT: 'Siria',
      JA: 'シリア',
      KO: '시리아',
    },
    'Palestine': {
      ES: 'Palestina',
      EN: 'Palestine',
      FR: 'Palestine',
      IT: 'Palestina',
      JA: 'パレスチナ',
      KO: '팔레스타인',
    },
    'Vietnam': {
      ES: 'Vietnam',
      EN: 'Vietnam',
      FR: 'Viêt Nam',
      IT: 'Vietnam',
      JA: 'ベトナム',
      KO: '베트ナム',
    },
    'Thailand': {
      ES: 'Tailandia',
      EN: 'Thailand',
      FR: 'Thaïlande',
      IT: 'Thailandia',
      JA: 'タイ',
      KO: '태국',
    },
    'Indonesia': {
      ES: 'Indonesia',
      EN: 'Indonesia',
      FR: 'Indonésie',
      IT: 'Indonesia',
      JA: 'インドネシア',
      KO: '인도네시아',
    },
    'India': {
      ES: 'India',
      EN: 'India',
      FR: 'Inde',
      IT: 'India',
      JA: 'インド',
      KO: '인도',
    },
    'Kyrgyzstan': {
      ES: 'Kirguistán',
      EN: 'Kyrgyzstan',
      FR: 'Kirghizistan',
      IT: 'Kirghizistan',
      JA: 'キルギス',
      KO: '키르기스스탄',
    },
    'Tajikistan': {
      ES: 'Tayikistán',
      EN: 'Tajikistan',
      FR: 'Tadjikistan',
      IT: 'Tagikistan',
      JA: 'タジキスタン',
      KO: '타지키스탄',
    },
    'Lebanon': {
      ES: 'Líbano',
      EN: 'Lebanon',
      FR: 'Liban',
      IT: 'Libano',
      JA: 'レバノン',
      KO: '레바논',
    },
    'North Korea': {
      ES: 'Corea del Norte',
      EN: 'North Korea',
      FR: 'Corée du Nord',
      IT: 'Corea del Nord',
      JA: '北朝鮮',
      KO: '북한',
    },
    'Kuwait': {
      ES: 'Kuwait',
      EN: 'Kuwait',
      FR: 'Koweït',
      IT: 'Kuwait',
      JA: 'クウェート',
      KO: '쿠웨이트',
    },
    'Yemen': {
      ES: 'Yemen',
      EN: 'Yemen',
      FR: 'Yémen',
      IT: 'Yemen',
      JA: 'イエメン',
      KO: '예멘',
    },
  };

  const cleanKey = Object.keys(translations).find(
    (key) => key.toLowerCase() === cleanName.toLowerCase()
  );

  if (cleanKey) {
    const upperLang = lang.toUpperCase();
    return translations[cleanKey][upperLang] || translations[cleanKey]['ES'] || name;
  }

  return name;
}
